#Project Info
includes:
- "common.yaml"
- "Objects/geometry/Polygon.h"
- "Objects/Grid.hpp"
- "Objects/Camera.h"
- "Objects/lighting/Light.h"
- "modeling/OurModels.cpp"
- "utils/GL_Error.h"
- "utils/objloader.cpp"
- "Opengl_a/Shader.h"
- "Common.h"
- <GL/glew.h>    
- <GLFW/glfw3.h> 
- <glm/gtc/matrix_transform.hpp>
- <glm/gtc/type_ptr.hpp>
- <glm/gtx/transform2.hpp>
- "utils/stb_image.h"
- <vector>
- <stdio.h>

contributor:
- name: "Benjamin Therien"
  id: 40034572
- name: "Sean Heinrichs"
  id: 40075789
- name: "Wayne Huras"
  id: 40074423
- name: "Isabelle Gourchette"
  id: 40008121
- name: "Ziming Wang"
  id: 40041601
 
Variables:
- name: "WINDOW_WIDTH"
  value: 1080
- name: "WINDOW_HEIGHT"
  value: 1080
- name: "SHADOW_WIDTH"
  value: 1024
- name: "SHADOW_HEIGHT"
  value: 1024
- name: "deltaTime"
  value: 0.0
- name: "lastFrame"
  value: 0.0
- name: "xOffset"
  value: 0.0
- name: "yOffset"
  value: 0.0
- name: "rX"
  value: 0.0
- name: "rY"
  value: 0.0
- name: "jumpCounter"
  value: 0
- name: "firstMouse"
  value: "true"
- name: "RED"
  value: 0.5
- name: "BLUE"
  value: 0.5
- name: "GREEN"
  value: 0.5
- name: "selected"
  value: 0
- name: "useTextures"
  value: 1
- name: "useShadows"
  value: "true"

  
  name: SHADOW_WIDTH
  value: 1024
  name: SHADOW_HEIGHT
  value: 1024
  name: deltaTime
  value: 0.0
  name: lastFrame
  value: 0.0
  name: xOffset
  value: 0.0
  name: yOffset
  value: 0.0
  name: rX
  value: 0.0
  name: rY
  value: 0.0
  name: jumpCounter
  value: 0
  name: firstMouse
  value: true
  name: RED
  value: 0.5
  name: BLUE
  value: 0.5
  name: GREEN
  value: 0.5
  name: selected
  value: 0
  name: useTextures
  value: 1
  name: useShadows
  value: true