Variables:
- name: SENSITIVITY
  value: 10
- name: WINDOW_HEIGHT
  value: 768
- name: SHADOW_WIDTH
  value: 1024
- name: SHADOW_HEIGHT
  value: 1024
- name: deltaTime
  value: 0.0
- name: lastFrame
  value: 0.0
- name: xOffset
  value: 0.0
- name: yOffset
  value: 0.0
- name: rX
  value: 0.0
- name: rY
  value: 0.0
- name: jumpCounter
  value: 0
- name: firstMouse
  value: true
- name: RED
  value: 0.5
- name: BLUE
  value: 0.5
- name: GREEN
  value: 0.5
- name: selected
  value: 0
- name: useTextures
  value: 1
- name: useShadows
  value: true