
Variables:
  # Set the time of day (DAY, NIGHT)
- name: TIME_OF_DAY
  value: DAY

  # Set the textures (1 = ON, 0 = OFF)
- name: useTextures
  value: 1

  # Set the shadows (true = ON, false = OFF)
- name: useShadows
  value: true

  #set to BIG or SMALL or NORMAL
  #Default option: 
  #terrainSize:SMALL && terrainTopography:REALSMOOTH
- name: terrainSize
  value: NORMAL

  #set to SMOOTH or HILLS or REALSMOOTH
- name: terrainTopography
  value: SMOOTH