Variables:
  # Set the time of day (DAY, NIGHT)
- name: TIME_OF_DAY
  value: DAY

  # Set the size of the terrain (SMALL, NORMAL, BIG) 
- name: TERRAIN_SIZE
  value: NORMAL

  # Set the shape of the terrain (SMOOTH, HILLS, REALSMOOTH)
- name: TERRAIN_TOPOGRAPHY
  value: SMOOTH

  # Set the textures (1 = ON, 0 = OFF)
- name: useTextures
  value: 1

  # Set the shadows (true = ON, false = OFF)
- name: useShadows
  value: true